database:
  host: "localhost"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "tinder_profile"
server:
  port: 8080
minio:
  endpoint: "127.0.0.1:9000"
  access_key: "AjVwVVB6Xwek7osJuW7C"
  secret_key: "1kkbfuj2OC2wqyqVbMHJkTpa8G9xpuCscMXLgBVO"
  bucket: "mybucket"
  secure: false
  use_ssl: false