database:
  host: "localhost"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "tinder_profile"
server:
  port: 8080
minio:
  endpoint: "localhost:9000"
  accessKey: "myuser"
  secretKey: "mypassword"
  bucket: "mybucket"
  secure: false
  useSSL: false