database:
  host: "db_pers"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "tinder_profile"
server:
  port: 8080
minio:
  endpoint: "minio_docker:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "mybucket"
  secure: false
  use_ssl: false
  host: "http://localhost:9000"
  pub_prefix: "pub"
rabbit:
  url: "rabbitmq:5672"
  queue_photo_name: ""
  queue_tags_name: ""
  queue_anket_name: ""